### ISSUE TITLE
error "error writing time request: timeout" - or "Unknown Data: 5100 [..]" (disappeared on restart)

### ISSUE THREAD

**Issue by Jimw338** [LoopKit/xDripG5#52]
I've finally managed to get the xDripG5-Example project.  (I think by opening up the xcWorkspace file instead of just the project - I might start a blog called "War With xCode".  I originally got a "unknown data: 51.." error - which didn't make sense as that looks like it's just a authStatusRxMessage.  I restarted the iPod and opened the app WITHOUT having the Dexcom app running, and it I guess got past that error.  (Both Stay Connected and Run Alongside are selected)

Now it manages to get past the authentication, but fails with "Error writing time request: timeout"  Does this mean that Dexcom has changed the "update interval" for the transmitter and so the app times out waiting for a response?  The sensor is going to end in 2 hours - could that affect things?

If I open the Dexcom app, it gives me the "Signal Lost" thing for about a minute (I assume waiting for the transmitter to send *something*), and then get a BG value (in the Dexcom app).  Then I close the Dexcom app (hitting the "Home" button - I assume it's still open in the background) and opening the xDrip example.

After closing the Dxcom app, it again gives me the "unknown data" error with a data string of "51000102e67b20016a62e004e010000c032312d" (different from before - I assume it's a different BG value) which again looks like a authStatusRxMessage.  Is this because the Dexcom app "opened" the sensor and sent the time request, and now the xDrip example can't process (or seemingly even recognize by opcode) the StatusRx for some reason?

Thanks,
Jim

**Comment by pi4ohhi7** [comment]
If I run both the Dexcom app and xDripG5 (with PassiveMode _disabled_) I also get a "51000..." message. I don't believe this is an AuthStatusRXMessage; the opcode for AuthStatusRXMessage is 0x05 (== 0x5), so that would appear as "05000...".

My best guess for your other troubles is that it's a combination of running xDripG5 with PassiveMode disabled alongside the official Dexcom app, and some Auth bugs that are currently in mainline (I opened a pull request to fix them). My guess is that the bugs cause xDripG5 to fail authentication which somehow messes with the official app communicating with the transmitter.

**Comment by ps2** [comment]
The code has changed a lot since this was filed.  Going to close; if there are still issues, please reopen them with steps to reproduce using current code.
